def hex_key(num):
    
    primes = [2, 3, 5, 7, 11, 13, 17]
    hex_primes = [2, 3, 5, 7, 11, 13, 17]
    for i in range(14, 22):
        hex_primes.append(i)
    hex_primes.append(20)
    hex_primes.append(22)
    hex_primes.append(23)
    hex_primes.append(25)
    hex_primes.append(27)
    hex_primes.append(29)
    hex_primes.append(2B)
    hex_primes.append(2D)
    hex_primes.append(2F)
    hex_primes.append(31)
    hex_primes.append(33)
    hex_primes.append(35)
    hex_primes.append(37)
    hex_primes.append(39)
    hex_primes.append(3B)
    hex_primes.append(3D)
    hex_primes.append(3F)
    hex_primes.append(41)
    hex_primes.append(43)
    hex_primes.append(45)
    hex_primes.append(47)
    hex_primes.append(49)
    hex_primes.append(4B)
    hex_primes.append(4D)
    hex_primes.append(4F)
    hex_primes.append(51)
    hex_primes.append(53)
    hex_primes.append(55)
    hex_primes.append(57)
    hex_primes.append(59)
    hex_primes.append(5B)
    hex_primes.append(5D)
    hex_primes.append(5F)
    hex_primes.append(61)
    hex_primes.append(63)
    hex_primes.