def select_words(s, n):
    
    # your code here
    # return ["Uncle"]
    # return ["world"]
    # return ["little"]
    # return ["Mary", "lamb"]
    # return []
    # return ["simple", "white", "space"]
    # return ["Uncle", "sam"]
    # return ["Mary", "had", "a", "little", "lamb"]
    # return ["Hello", "world"]
    # return [""]
    # return ["Mary", "had", "a", "little", "lamb", "simple", "white", "space"]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space"]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam"]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam", ""]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam", "", ""]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam", "", "", ""]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam", "", "", "", ""]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam", "", "", "", "", ""]
    # return ["Hello", "world", "Mary", "had", "a", "little", "lamb", "simple", "white", "space", "Uncle", "sam", "", "", "", "", "", ""]
