def pairs_sum_to_zero(l):
    
    # return True if there are two distinct elements in the list that sum to zero, and False otherwise.
    # Hint: Keep track of which numbers have been checked so that you don't check them again.
    # return False
    # return True
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False
    # return False