
def f1(n, m, k, x_i, y_i, w_i, a_i, b_i):
    # your code here
    return total_cost

def f2(...):
    # your code here
    return ...

if __name__ == '__main__':
    n = ...
    m = ...
    k = ...
    x_i = ...
    y_i = ...
    w_i = ...
    a_i = ...
    b_i = ...
    total_cost = f1(n, m, k, x_i, y_i, w_i, a_i, b_i)
    print(total_cost)

