def Strongest_Extension(class_name, extensions):
    
    # Write your code here
    # extensions = ['AA', 'Be', 'CC']
    # class_name = 'my_class'
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    # return Strongest_Extension(class_name, extensions)
    #