def triples_sum_to_zero(l: list):
    
    # hint: use set()
    # hint: use combinations()
    # hint: use sum()
    # hint: use len()
    # hint: use a for loop
    # hint: use a while loop
    # hint: use a return statement
    # hint: use a break statement
    # hint: use a bool()
    # hint: use a set()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    # hint: use a list()
    #