def even_odd_count(num):
    
    # return (num.count("0"), num.count("1"))
    # return (num.count("2"), num.count("3"))
    # return (num.count("4"), num.count("5"))
    # return (num.count("6"), num.count("7"))
    # return (num.count("8"), num.count("9"))
    # return (num.count("0"), num.count("1"))
    # return (num.count("2"), num.count("3"))
    # return (num.count("4"), num.count("5"))
    # return (num.count("6"), num.count("7"))
    # return (num.count("8"), num.count("9"))
    # return (num.count("0"), num.count("1"))
    # return (num.count("2"), num.count("3"))
    # return (num.count("4"), num.count("5"))
    # return (num.count("6"), num.count("7"))
    # return (num.count("8"), num.count("9"))
    # return (num.count("0"), num.count("1"))
    # return (num.count("2"), num.count("3"))
    # return (num.count("4"), num.count("5"))
    # return (num.count("6"), num.count("7"))
    # return (num.count("8"), num.count("9"))
    # return (num.count("0"), num.count("1"))
    # return (num.count("2"), num.count("3"))
    # return (num.count("4"), num.count("5"))
    # return (num.count("6"), num.count("7"))
    # return (num.count("8"), num.count("9"))
    # return (num.count("0"), num.count("1"))
    # return (num.count("2"), num.count("3"))
    # return (num.count("4"), num.count("5"))
    # return (num.count("6"), num.count("7"))
    # return (num.count("8"), num.count("9"))
   