def minSubArraySum(nums):
    
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n) time | O(1) space
    # O(n