
def f1(n, s):
    # your code here
    return ...

def f2(...):
    # your code here
    return ...

if __name__ == '__main__':
    n = ...
    s = ...
    predictions = ...
    sorted_predictions = f1(n, s, predictions)
    print(sorted_predictions)

