def Strongest_Extension(class_name, extensions):
    
    # your code here
    class_name = class_name.lower()
    class_name = class_name.upper()
    class_name = class_name.capitalize()
    class_name = class_name.title()
    class_name = class_name.swapcase()
    class_name = class_name.casefold()
    class_name = class_name.center(10)
    class_name = class_name.expandtabs(10)
    class_name = class_name.ljust(10)
    class_name = class_name.rjust(10)
    class_name = class_name.zfill(10)
    class_name = class_name.isalnum()
    class_name = class_name.isalpha()
    class_name = class_name.isdecimal()
    class_name = class_name.isdigit()
    class_name = class_name.isidentifier()
    class_name = class_name.islower()
    class_name = class_name.isnumeric()
    class_name = class_name.isprintable()
    class_name = class_name.isspace()
    class_name = class_name.istitle()
    class_name = class_name.isupper()
    class_name = class_name.join(extensions)
    class_name = class_name.lstrip(extensions)
    class_name = class_name.rstrip(extensions)
    class_name = class_name.strip(extensions)
    class_name = class_name.partition(extensions)
    class_name = class_name.rpartition(extensions)
    class_name = class_name.replace(extensions, extensions)
    class_name = class_name.split(extensions)
    class_name = class_name.rsplit(extensions)
    class_name = class_name.splitlines(extensions)
    class_name = class_name.startswith(extensions)
    class_name = class_name.endswith(extensions)
    class_name = class_name.find(extensions)
    class_name = class_name.rfind(extensions)
    class_name = class_name.index(extensions)
    class_name = class_name.rindex(extensions)
    class_name = class_name.count(extensions)
    class_