def skjkasdkd(lst):
    
    lst = sorted(lst)
    lst = [int(i) for i in lst]
    lst = [i for i in lst if i > 1]
    lst = [i for i in lst if i % 2 == 0]
    lst = [i for i in lst if i % 3 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 7 == 0]
    lst = [i for i in lst if i % 4 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 2 == 0]
    lst = [i for i in lst if i % 3 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 7 == 0]
    lst = [i for i in lst if i % 4 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 2 == 0]
    lst = [i for i in lst if i % 3 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 7 == 0]
    lst = [i for i in lst if i % 4 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 2 == 0]
    lst = [i for i in lst if i % 3 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 7 == 0]
    lst = [i for i in lst if i % 4 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 2 == 0]
    lst = [i for i in lst