def skjkasdkd(lst):
    
    lst = sorted(lst)
    lst = [int(i) for i in lst]
    lst = [i for i in lst if i > 1]
    lst = [i for i in lst if i % 2 == 0]
    lst = [i for i in lst if i % 3 == 0]
    lst = [i for i in lst if i % 5 == 0]
    lst = [i for i in lst if i % 7 == 0]
    lst = [i for i in lst if i % 11 == 0]
    lst = [i for i in lst if i % 13 == 0]
    lst = [i for i in lst if i % 17 == 0]
    lst = [i for i in lst if i % 19 == 0]
    lst = [i for i in lst if i % 23 == 0]
    lst = [i for i in lst if i % 29 == 0]
    lst = [i for i in lst if i % 31 == 0]
    lst = [i for i in lst if i % 37 == 0]
    lst = [i for i in lst if i % 41 == 0]
    lst = [i for i in lst if i % 43 == 0]
    lst = [i for i in lst if i % 47 == 0]
    lst = [i for i in lst if i % 53 == 0]
    lst = [i for i in lst if i % 59 == 0]
    lst = [i for i in lst if i % 61 == 0]
    lst = [i for i in lst if i % 67 == 0]
    lst = [i for i in lst if i % 71 == 0]
    lst = [i for i in lst if i % 73 == 0]
    lst = [i for i in lst if i % 79 == 0]
    lst = [i for i in lst if i % 83 == 0]
    lst = [i for i in lst if i % 89 == 0]
    lst = [i for i in lst if i % 97 == 0]
    lst = [i for