def skjkasdkd(lst):
    
    lst = [x for x in lst if x > 0]
    lst = [x for x in lst if x % 2 != 0]
    lst = [x for x in lst if x % 3 != 0]
    lst = [x for x in lst if x % 5 != 0]
    lst = [x for x in lst if x % 7 != 0]
    lst = [x for x in lst if x % 11 != 0]
    lst = [x for x in lst if x % 13 != 0]
    lst = [x for x in lst if x % 17 != 0]
    lst = [x for x in lst if x % 19 != 0]
    lst = [x for x in lst if x % 23 != 0]
    lst = [x for x in lst if x % 29 != 0]
    lst = [x for x in lst if x % 31 != 0]
    lst = [x for x in lst if x % 37 != 0]
    lst = [x for x in lst if x % 41 != 0]
    lst = [x for x in lst if x % 43 != 0]
    lst = [x for x in lst if x % 47 != 0]
    lst = [x for x in lst if x % 53 != 0]
    lst = [x for x in lst if x % 59 != 0]
    lst = [x for x in lst if x % 61 != 0]
    lst = [x for x in lst if x % 67 != 0]
    lst = [x for x in lst if x % 71 != 0]
    lst = [x for x in lst if x % 73 != 0]
    lst = [x for x in lst if x % 79 != 0]
    lst = [x for x in lst if x % 83 != 0]
    lst = [x for x in lst if x % 89 != 0]
    lst = [x for x in lst if x % 97 != 0]