def triples_sum_to_zero(l: list):
    
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
    # TODO: implement this function
   