from typing import List


def parse_music(music_string: str) -> List[int]:
    
    music_string = music_string.replace(" ", "")
    music_string = music_string.replace("|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.replace("o|", "")
    music_string = music_string.replace(".", "")
    music_string = music_string.replace("o", "")
    music_string = music_string.