
def can_transfer_all_data(n, q, s, queues, sensors, windows):
    # Initialize a queue for each sensor
    sensor_queues = [[] for _ in range(s)]
    
    # Initialize a queue for each FIFO queue
    fifo_queues = [[] for _ in range(q)]
    
    # Loop through each downlink window
    for window in windows:
        # Get the amount of data that can be transferred in this window
        data_transferred = window[0]
        
        # Loop through each sensor
        for i in range(s):
            # Get the amount of data generated by this sensor
            sensor_data = window[i + 1]
            
            # Add the sensor data to the sensor queue
            sensor_queues[i].append(sensor_data)
            
            # Add the sensor data to the FIFO queue
            fifo_queues[queues[i] - 1].append(sensor_data)
    
    # Loop through each FIFO queue
    for queue in fifo_queues:
        # Check if the queue is empty
        if queue:
            # Check if the data in the queue can be transferred in this window
            if sum(queue) > data_transferred:
                return "impossible"
    
    # Check if all sensor queues are empty
    for queue in sensor_queues:
        if queue:
            return "impossible"
    
    return "possible"

