
def is_possible(n, q, s, q_list, c_list, d_list, a_list):
    # Initialize a queue to store the data
    queue = []

    # Iterate through each downlink window
    for i in range(n):
        # Get the amount of data that can be transferred during this window
        data_transferred = d_list[i]

        # Iterate through each sensor
        for j in range(s):
            # Get the queue that the sensor feeds its data into
            queue_index = q_list[j] - 1

            # Get the amount of data generated by the sensor during this window
            data_generated = a_list[j]

            # Check if the queue has enough space to store the data
            if data_transferred >= data_generated:
                # Add the data to the queue
                queue.append(data_generated)

                # Subtract the data from the amount of data that can be transferred during this window
                data_transferred -= data_generated
            else:
                # The queue is full, so the data is lost
                return "impossible"

    # Check if all data has been transferred
    if len(queue) == 0:
        return "possible"
    else:
        return "impossible"

