
def is_possible(n, q, s, q_list, c_list, d_list, a_list):
    # Initialize a queue to store the data
    queue = []

    # Iterate through each downlink window
    for i in range(n):
        # Get the amount of data that can be transferred during this window
        d = d_list[i]

        # Iterate through each sensor
        for j in range(s):
            # Get the queue that the sensor feeds its data into
            q_idx = q_list[j]

            # Get the amount of data generated by the sensor during this window
            a = a_list[i][j]

            # Check if the queue has enough space to store the data
            if c_list[q_idx] - len(queue) >= a:
                # Add the data to the queue
                queue.extend([a] * a)
            else:
                # The queue is full, so the data is lost
                return "impossible"

    # Check if all data can be transferred to Earth
    if len(queue) <= d:
        return "possible"
    else:
        return "impossible"

