
def is_possible(n, q, s, q_list, c_list, d_list, a_list):
    # Initialize a queue to store the data
    queue = []

    # Iterate through each downlink window
    for i in range(n):
        # Add the data generated by each sensor to the queue
        for j in range(s):
            queue.append(a_list[i][j])

        # Check if the queue is full
        if len(queue) > c_list[q_list[i] - 1]:
            return "impossible"

        # Remove the data that can be transmitted during this window
        queue = queue[d_list[i]:]

    # Check if all data has been transferred
    if len(queue) == 0:
        return "possible"
    else:
        return "impossible"

